Fix config??
xornet-cloud/Xornet pull request #181
Opened 2021-06-29 01:55 UTC by Faunsce

2021-06-29 01:58 UTC, Geoxor requested changes

2021-06-29 01:58 UTC, Geoxor commented on client/vue.config.js
> +let dev = process.env.NODE_ENV === "development" ? true : false;
where do you set the env variable

2021-06-29 13:21 UTC, merged

2021-07-03 21:59 UTC, Faunsce commented
Fixed #156

2021-07-03 22:00 UTC, Faunsce commented on client/vue.config.js
> +let dev = process.env.NODE_ENV === "development" ? true : false;
The variable is set by the build process. https://cli.vuejs.org/config/#global-cli-config